# Generated by Django 6.0.3 on 2026-03-04 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_image', models.ImageField(upload_to='item/')),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.category')),
            ],
        ),
    ]
