# Generated by Django 6.0.3 on 2026-03-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_sizes',
            field=models.ManyToManyField(blank=True, to='ecommerceApp.size'),
        ),
    ]
