# Generated by Django 6.0.3 on 2026-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_size_item_item_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_colors',
            field=models.ManyToManyField(blank=True, to='ecommerceApp.color'),
        ),
    ]
