# Generated by Django 6.0.3 on 2026-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0004_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
